### ISSUE TITLE
Clarify handling of masks

### ISSUE THREAD

**Issue by cod3monk** [RRZE-HPC/OSACA#24]
With AVX512 instructions are mostly defined with masking support and not without. E.g., https://hjlebbink.github.io/x86doc/html/ADDPD.html. The ZMM version is defined with masking, but also works without. This needs to be considered when searching for instruction forms in the CSV.

As a workaround I am duplicating all instructions with masking support, with `{opmask}` stripped from it: https://github.com/RRZE-HPC/OSACA/blob/imported_intel_models/osaca/data/model_importer.py#L139

**Comment by JanLJL** [comment]
Instruction forms can contain a `mask` and `zeroing` attribute, indicating the mask register and the addition `{z}` for zeroing, e.g.:
```yml
- name: VFMADD213PD
  operands:
  - class: register
    name: zmm
  - class: register
    name: zmm
  - class: register
    name: zmm
    mask: k
    zeroing: z
```
Both `mask` and `zeroing` can use wildcars (`"*"`).
With commit 1aa710f19523e7c358feee3e3bb80d29a1d4ccd6 we also added the support of differentiating between masking/zeroing while fetching the performance data from the DB.
